<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SurahSeeder extends Seeder
{
    public function run(): void
    {
        // Skip if already seeded
        if (DB::table('surahs')->count() === 114) {
            return;
        }

        DB::table('surahs')->insertOrIgnore([
            ['id' => 1,   'name_ar' => 'الفاتحة',    'name_en' => 'Al-Fatihah',    'name_transliteration' => 'Al-Fatihah',    'total_ayahs' => 7,   'juz_start' => 1,  'page_start' => 1,   'revelation_type' => 'meccan'],
            ['id' => 2,   'name_ar' => 'البقرة',      'name_en' => 'Al-Baqarah',    'name_transliteration' => 'Al-Baqarah',    'total_ayahs' => 286, 'juz_start' => 1,  'page_start' => 2,   'revelation_type' => 'medinan'],
            ['id' => 3,   'name_ar' => 'آل عمران',    'name_en' => 'Ali Imran',     'name_transliteration' => 'Ali-Imran',     'total_ayahs' => 200, 'juz_start' => 3,  'page_start' => 50,  'revelation_type' => 'medinan'],
            ['id' => 4,   'name_ar' => 'النساء',      'name_en' => 'An-Nisa',       'name_transliteration' => 'An-Nisa',       'total_ayahs' => 176, 'juz_start' => 4,  'page_start' => 77,  'revelation_type' => 'medinan'],
            ['id' => 5,   'name_ar' => 'المائدة',     'name_en' => "Al-Ma'idah",    'name_transliteration' => 'Al-Maidah',     'total_ayahs' => 120, 'juz_start' => 6,  'page_start' => 106, 'revelation_type' => 'medinan'],
            ['id' => 6,   'name_ar' => 'الأنعام',     'name_en' => "Al-An'am",      'name_transliteration' => 'Al-Anam',       'total_ayahs' => 165, 'juz_start' => 7,  'page_start' => 128, 'revelation_type' => 'meccan'],
            ['id' => 7,   'name_ar' => 'الأعراف',     'name_en' => "Al-A'raf",      'name_transliteration' => 'Al-Araf',       'total_ayahs' => 206, 'juz_start' => 8,  'page_start' => 151, 'revelation_type' => 'meccan'],
            ['id' => 8,   'name_ar' => 'الأنفال',     'name_en' => 'Al-Anfal',      'name_transliteration' => 'Al-Anfal',      'total_ayahs' => 75,  'juz_start' => 9,  'page_start' => 177, 'revelation_type' => 'medinan'],
            ['id' => 9,   'name_ar' => 'التوبة',      'name_en' => 'At-Tawbah',     'name_transliteration' => 'At-Tawbah',     'total_ayahs' => 129, 'juz_start' => 10, 'page_start' => 187, 'revelation_type' => 'medinan'],
            ['id' => 10,  'name_ar' => 'يونس',        'name_en' => 'Yunus',         'name_transliteration' => 'Yunus',         'total_ayahs' => 109, 'juz_start' => 11, 'page_start' => 208, 'revelation_type' => 'meccan'],
            ['id' => 11,  'name_ar' => 'هود',         'name_en' => 'Hud',           'name_transliteration' => 'Hud',           'total_ayahs' => 123, 'juz_start' => 11, 'page_start' => 221, 'revelation_type' => 'meccan'],
            ['id' => 12,  'name_ar' => 'يوسف',        'name_en' => 'Yusuf',         'name_transliteration' => 'Yusuf',         'total_ayahs' => 111, 'juz_start' => 12, 'page_start' => 235, 'revelation_type' => 'meccan'],
            ['id' => 13,  'name_ar' => 'الرعد',       'name_en' => "Ar-Ra'd",       'name_transliteration' => 'Ar-Rad',        'total_ayahs' => 43,  'juz_start' => 13, 'page_start' => 249, 'revelation_type' => 'medinan'],
            ['id' => 14,  'name_ar' => 'إبراهيم',     'name_en' => 'Ibrahim',       'name_transliteration' => 'Ibrahim',       'total_ayahs' => 52,  'juz_start' => 13, 'page_start' => 255, 'revelation_type' => 'meccan'],
            ['id' => 15,  'name_ar' => 'الحجر',       'name_en' => 'Al-Hijr',       'name_transliteration' => 'Al-Hijr',       'total_ayahs' => 99,  'juz_start' => 14, 'page_start' => 262, 'revelation_type' => 'meccan'],
            ['id' => 16,  'name_ar' => 'النحل',       'name_en' => 'An-Nahl',       'name_transliteration' => 'An-Nahl',       'total_ayahs' => 128, 'juz_start' => 14, 'page_start' => 267, 'revelation_type' => 'meccan'],
            ['id' => 17,  'name_ar' => 'الإسراء',     'name_en' => "Al-Isra'",      'name_transliteration' => 'Al-Isra',       'total_ayahs' => 111, 'juz_start' => 15, 'page_start' => 282, 'revelation_type' => 'meccan'],
            ['id' => 18,  'name_ar' => 'الكهف',       'name_en' => 'Al-Kahf',       'name_transliteration' => 'Al-Kahf',       'total_ayahs' => 110, 'juz_start' => 15, 'page_start' => 293, 'revelation_type' => 'meccan'],
            ['id' => 19,  'name_ar' => 'مريم',        'name_en' => 'Maryam',        'name_transliteration' => 'Maryam',        'total_ayahs' => 98,  'juz_start' => 16, 'page_start' => 305, 'revelation_type' => 'meccan'],
            ['id' => 20,  'name_ar' => 'طه',          'name_en' => 'Ta-Ha',         'name_transliteration' => 'Ta-Ha',         'total_ayahs' => 135, 'juz_start' => 16, 'page_start' => 312, 'revelation_type' => 'meccan'],
            ['id' => 21,  'name_ar' => 'الأنبياء',    'name_en' => "Al-Anbiya'",    'name_transliteration' => 'Al-Anbiya',     'total_ayahs' => 112, 'juz_start' => 17, 'page_start' => 322, 'revelation_type' => 'meccan'],
            ['id' => 22,  'name_ar' => 'الحج',        'name_en' => 'Al-Hajj',       'name_transliteration' => 'Al-Hajj',       'total_ayahs' => 78,  'juz_start' => 17, 'page_start' => 332, 'revelation_type' => 'medinan'],
            ['id' => 23,  'name_ar' => 'المؤمنون',    'name_en' => "Al-Mu'minun",   'name_transliteration' => 'Al-Muminun',    'total_ayahs' => 118, 'juz_start' => 18, 'page_start' => 342, 'revelation_type' => 'meccan'],
            ['id' => 24,  'name_ar' => 'النور',       'name_en' => 'An-Nur',        'name_transliteration' => 'An-Nur',        'total_ayahs' => 64,  'juz_start' => 18, 'page_start' => 350, 'revelation_type' => 'medinan'],
            ['id' => 25,  'name_ar' => 'الفرقان',     'name_en' => 'Al-Furqan',     'name_transliteration' => 'Al-Furqan',     'total_ayahs' => 77,  'juz_start' => 18, 'page_start' => 359, 'revelation_type' => 'meccan'],
            ['id' => 26,  'name_ar' => 'الشعراء',     'name_en' => "Ash-Shu'ara'",  'name_transliteration' => 'Ash-Shuara',    'total_ayahs' => 227, 'juz_start' => 19, 'page_start' => 367, 'revelation_type' => 'meccan'],
            ['id' => 27,  'name_ar' => 'النمل',       'name_en' => 'An-Naml',       'name_transliteration' => 'An-Naml',       'total_ayahs' => 93,  'juz_start' => 19, 'page_start' => 377, 'revelation_type' => 'meccan'],
            ['id' => 28,  'name_ar' => 'القصص',       'name_en' => 'Al-Qasas',      'name_transliteration' => 'Al-Qasas',      'total_ayahs' => 88,  'juz_start' => 20, 'page_start' => 385, 'revelation_type' => 'meccan'],
            ['id' => 29,  'name_ar' => 'العنكبوت',    'name_en' => 'Al-Ankabut',    'name_transliteration' => 'Al-Ankabut',    'total_ayahs' => 69,  'juz_start' => 20, 'page_start' => 396, 'revelation_type' => 'meccan'],
            ['id' => 30,  'name_ar' => 'الروم',       'name_en' => 'Ar-Rum',        'name_transliteration' => 'Ar-Rum',        'total_ayahs' => 60,  'juz_start' => 21, 'page_start' => 404, 'revelation_type' => 'meccan'],
            ['id' => 31,  'name_ar' => 'لقمان',       'name_en' => 'Luqman',        'name_transliteration' => 'Luqman',        'total_ayahs' => 34,  'juz_start' => 21, 'page_start' => 411, 'revelation_type' => 'meccan'],
            ['id' => 32,  'name_ar' => 'السجدة',      'name_en' => 'As-Sajdah',     'name_transliteration' => 'As-Sajdah',     'total_ayahs' => 30,  'juz_start' => 21, 'page_start' => 415, 'revelation_type' => 'meccan'],
            ['id' => 33,  'name_ar' => 'الأحزاب',     'name_en' => 'Al-Ahzab',      'name_transliteration' => 'Al-Ahzab',      'total_ayahs' => 73,  'juz_start' => 21, 'page_start' => 418, 'revelation_type' => 'medinan'],
            ['id' => 34,  'name_ar' => 'سبأ',         'name_en' => 'Saba',          'name_transliteration' => 'Saba',          'total_ayahs' => 54,  'juz_start' => 22, 'page_start' => 428, 'revelation_type' => 'meccan'],
            ['id' => 35,  'name_ar' => 'فاطر',        'name_en' => 'Fatir',         'name_transliteration' => 'Fatir',         'total_ayahs' => 45,  'juz_start' => 22, 'page_start' => 434, 'revelation_type' => 'meccan'],
            ['id' => 36,  'name_ar' => 'يس',          'name_en' => 'Ya-Sin',        'name_transliteration' => 'Ya-Sin',        'total_ayahs' => 83,  'juz_start' => 22, 'page_start' => 440, 'revelation_type' => 'meccan'],
            ['id' => 37,  'name_ar' => 'الصافات',     'name_en' => 'As-Saffat',     'name_transliteration' => 'As-Saffat',     'total_ayahs' => 182, 'juz_start' => 23, 'page_start' => 446, 'revelation_type' => 'meccan'],
            ['id' => 38,  'name_ar' => 'ص',           'name_en' => 'Sad',           'name_transliteration' => 'Sad',           'total_ayahs' => 88,  'juz_start' => 23, 'page_start' => 453, 'revelation_type' => 'meccan'],
            ['id' => 39,  'name_ar' => 'الزمر',       'name_en' => 'Az-Zumar',      'name_transliteration' => 'Az-Zumar',      'total_ayahs' => 75,  'juz_start' => 23, 'page_start' => 458, 'revelation_type' => 'meccan'],
            ['id' => 40,  'name_ar' => 'غافر',        'name_en' => 'Ghafir',        'name_transliteration' => 'Ghafir',        'total_ayahs' => 85,  'juz_start' => 24, 'page_start' => 467, 'revelation_type' => 'meccan'],
            ['id' => 41,  'name_ar' => 'فصلت',        'name_en' => 'Fussilat',      'name_transliteration' => 'Fussilat',      'total_ayahs' => 54,  'juz_start' => 24, 'page_start' => 477, 'revelation_type' => 'meccan'],
            ['id' => 42,  'name_ar' => 'الشورى',      'name_en' => 'Ash-Shura',     'name_transliteration' => 'Ash-Shura',     'total_ayahs' => 53,  'juz_start' => 25, 'page_start' => 483, 'revelation_type' => 'meccan'],
            ['id' => 43,  'name_ar' => 'الزخرف',      'name_en' => 'Az-Zukhruf',    'name_transliteration' => 'Az-Zukhruf',    'total_ayahs' => 89,  'juz_start' => 25, 'page_start' => 489, 'revelation_type' => 'meccan'],
            ['id' => 44,  'name_ar' => 'الدخان',      'name_en' => 'Ad-Dukhan',     'name_transliteration' => 'Ad-Dukhan',     'total_ayahs' => 59,  'juz_start' => 25, 'page_start' => 496, 'revelation_type' => 'meccan'],
            ['id' => 45,  'name_ar' => 'الجاثية',     'name_en' => 'Al-Jathiyah',   'name_transliteration' => 'Al-Jathiyah',   'total_ayahs' => 37,  'juz_start' => 25, 'page_start' => 499, 'revelation_type' => 'meccan'],
            ['id' => 46,  'name_ar' => 'الأحقاف',     'name_en' => 'Al-Ahqaf',      'name_transliteration' => 'Al-Ahqaf',      'total_ayahs' => 35,  'juz_start' => 26, 'page_start' => 502, 'revelation_type' => 'meccan'],
            ['id' => 47,  'name_ar' => 'محمد',        'name_en' => 'Muhammad',      'name_transliteration' => 'Muhammad',      'total_ayahs' => 38,  'juz_start' => 26, 'page_start' => 507, 'revelation_type' => 'medinan'],
            ['id' => 48,  'name_ar' => 'الفتح',       'name_en' => 'Al-Fath',       'name_transliteration' => 'Al-Fath',       'total_ayahs' => 29,  'juz_start' => 26, 'page_start' => 511, 'revelation_type' => 'medinan'],
            ['id' => 49,  'name_ar' => 'الحجرات',     'name_en' => 'Al-Hujurat',    'name_transliteration' => 'Al-Hujurat',    'total_ayahs' => 18,  'juz_start' => 26, 'page_start' => 515, 'revelation_type' => 'medinan'],
            ['id' => 50,  'name_ar' => 'ق',           'name_en' => 'Qaf',           'name_transliteration' => 'Qaf',           'total_ayahs' => 45,  'juz_start' => 26, 'page_start' => 518, 'revelation_type' => 'meccan'],
            ['id' => 51,  'name_ar' => 'الذاريات',    'name_en' => 'Adh-Dhariyat',  'name_transliteration' => 'Adh-Dhariyat',  'total_ayahs' => 60,  'juz_start' => 26, 'page_start' => 520, 'revelation_type' => 'meccan'],
            ['id' => 52,  'name_ar' => 'الطور',       'name_en' => 'At-Tur',        'name_transliteration' => 'At-Tur',        'total_ayahs' => 49,  'juz_start' => 27, 'page_start' => 523, 'revelation_type' => 'meccan'],
            ['id' => 53,  'name_ar' => 'النجم',       'name_en' => 'An-Najm',       'name_transliteration' => 'An-Najm',       'total_ayahs' => 62,  'juz_start' => 27, 'page_start' => 526, 'revelation_type' => 'meccan'],
            ['id' => 54,  'name_ar' => 'القمر',       'name_en' => 'Al-Qamar',      'name_transliteration' => 'Al-Qamar',      'total_ayahs' => 55,  'juz_start' => 27, 'page_start' => 528, 'revelation_type' => 'meccan'],
            ['id' => 55,  'name_ar' => 'الرحمن',      'name_en' => 'Ar-Rahman',     'name_transliteration' => 'Ar-Rahman',     'total_ayahs' => 78,  'juz_start' => 27, 'page_start' => 531, 'revelation_type' => 'medinan'],
            ['id' => 56,  'name_ar' => 'الواقعة',     'name_en' => "Al-Waqi'ah",    'name_transliteration' => 'Al-Waqiah',     'total_ayahs' => 96,  'juz_start' => 27, 'page_start' => 534, 'revelation_type' => 'meccan'],
            ['id' => 57,  'name_ar' => 'الحديد',      'name_en' => 'Al-Hadid',      'name_transliteration' => 'Al-Hadid',      'total_ayahs' => 29,  'juz_start' => 27, 'page_start' => 537, 'revelation_type' => 'medinan'],
            ['id' => 58,  'name_ar' => 'المجادلة',    'name_en' => 'Al-Mujadila',   'name_transliteration' => 'Al-Mujadila',   'total_ayahs' => 22,  'juz_start' => 28, 'page_start' => 542, 'revelation_type' => 'medinan'],
            ['id' => 59,  'name_ar' => 'الحشر',       'name_en' => 'Al-Hashr',      'name_transliteration' => 'Al-Hashr',      'total_ayahs' => 24,  'juz_start' => 28, 'page_start' => 545, 'revelation_type' => 'medinan'],
            ['id' => 60,  'name_ar' => 'الممتحنة',    'name_en' => 'Al-Mumtahanah', 'name_transliteration' => 'Al-Mumtahanah', 'total_ayahs' => 13,  'juz_start' => 28, 'page_start' => 549, 'revelation_type' => 'medinan'],
            ['id' => 61,  'name_ar' => 'الصف',        'name_en' => 'As-Saf',        'name_transliteration' => 'As-Saf',        'total_ayahs' => 14,  'juz_start' => 28, 'page_start' => 551, 'revelation_type' => 'medinan'],
            ['id' => 62,  'name_ar' => 'الجمعة',      'name_en' => "Al-Jumu'ah",    'name_transliteration' => 'Al-Jumuah',     'total_ayahs' => 11,  'juz_start' => 28, 'page_start' => 553, 'revelation_type' => 'medinan'],
            ['id' => 63,  'name_ar' => 'المنافقون',   'name_en' => 'Al-Munafiqun',  'name_transliteration' => 'Al-Munafiqun',  'total_ayahs' => 11,  'juz_start' => 28, 'page_start' => 554, 'revelation_type' => 'medinan'],
            ['id' => 64,  'name_ar' => 'التغابن',     'name_en' => 'At-Taghabun',   'name_transliteration' => 'At-Taghabun',   'total_ayahs' => 18,  'juz_start' => 28, 'page_start' => 556, 'revelation_type' => 'medinan'],
            ['id' => 65,  'name_ar' => 'الطلاق',      'name_en' => 'At-Talaq',      'name_transliteration' => 'At-Talaq',      'total_ayahs' => 12,  'juz_start' => 28, 'page_start' => 558, 'revelation_type' => 'medinan'],
            ['id' => 66,  'name_ar' => 'التحريم',     'name_en' => 'At-Tahrim',     'name_transliteration' => 'At-Tahrim',     'total_ayahs' => 12,  'juz_start' => 28, 'page_start' => 560, 'revelation_type' => 'medinan'],
            ['id' => 67,  'name_ar' => 'الملك',       'name_en' => 'Al-Mulk',       'name_transliteration' => 'Al-Mulk',       'total_ayahs' => 30,  'juz_start' => 29, 'page_start' => 562, 'revelation_type' => 'meccan'],
            ['id' => 68,  'name_ar' => 'القلم',       'name_en' => 'Al-Qalam',      'name_transliteration' => 'Al-Qalam',      'total_ayahs' => 52,  'juz_start' => 29, 'page_start' => 564, 'revelation_type' => 'meccan'],
            ['id' => 69,  'name_ar' => 'الحاقة',      'name_en' => 'Al-Haqqah',     'name_transliteration' => 'Al-Haqqah',     'total_ayahs' => 52,  'juz_start' => 29, 'page_start' => 566, 'revelation_type' => 'meccan'],
            ['id' => 70,  'name_ar' => 'المعارج',     'name_en' => "Al-Ma'arij",    'name_transliteration' => 'Al-Maarij',     'total_ayahs' => 44,  'juz_start' => 29, 'page_start' => 568, 'revelation_type' => 'meccan'],
            ['id' => 71,  'name_ar' => 'نوح',         'name_en' => 'Nuh',           'name_transliteration' => 'Nuh',           'total_ayahs' => 28,  'juz_start' => 29, 'page_start' => 570, 'revelation_type' => 'meccan'],
            ['id' => 72,  'name_ar' => 'الجن',        'name_en' => 'Al-Jinn',       'name_transliteration' => 'Al-Jinn',       'total_ayahs' => 28,  'juz_start' => 29, 'page_start' => 572, 'revelation_type' => 'meccan'],
            ['id' => 73,  'name_ar' => 'المزمل',      'name_en' => 'Al-Muzzammil',  'name_transliteration' => 'Al-Muzzammil',  'total_ayahs' => 20,  'juz_start' => 29, 'page_start' => 574, 'revelation_type' => 'meccan'],
            ['id' => 74,  'name_ar' => 'المدثر',      'name_en' => 'Al-Muddaththir','name_transliteration' => 'Al-Muddaththir','total_ayahs' => 56,  'juz_start' => 29, 'page_start' => 575, 'revelation_type' => 'meccan'],
            ['id' => 75,  'name_ar' => 'القيامة',     'name_en' => 'Al-Qiyamah',    'name_transliteration' => 'Al-Qiyamah',    'total_ayahs' => 40,  'juz_start' => 29, 'page_start' => 577, 'revelation_type' => 'meccan'],
            ['id' => 76,  'name_ar' => 'الإنسان',     'name_en' => 'Al-Insan',      'name_transliteration' => 'Al-Insan',      'total_ayahs' => 31,  'juz_start' => 29, 'page_start' => 578, 'revelation_type' => 'medinan'],
            ['id' => 77,  'name_ar' => 'المرسلات',    'name_en' => 'Al-Mursalat',   'name_transliteration' => 'Al-Mursalat',   'total_ayahs' => 50,  'juz_start' => 29, 'page_start' => 580, 'revelation_type' => 'meccan'],
            ['id' => 78,  'name_ar' => 'النبأ',       'name_en' => "An-Naba'",      'name_transliteration' => 'An-Naba',       'total_ayahs' => 40,  'juz_start' => 30, 'page_start' => 582, 'revelation_type' => 'meccan'],
            ['id' => 79,  'name_ar' => 'النازعات',    'name_en' => "An-Nazi'at",    'name_transliteration' => 'An-Naziat',     'total_ayahs' => 46,  'juz_start' => 30, 'page_start' => 583, 'revelation_type' => 'meccan'],
            ['id' => 80,  'name_ar' => 'عبس',         'name_en' => 'Abasa',         'name_transliteration' => 'Abasa',         'total_ayahs' => 42,  'juz_start' => 30, 'page_start' => 585, 'revelation_type' => 'meccan'],
            ['id' => 81,  'name_ar' => 'التكوير',     'name_en' => 'At-Takwir',     'name_transliteration' => 'At-Takwir',     'total_ayahs' => 29,  'juz_start' => 30, 'page_start' => 586, 'revelation_type' => 'meccan'],
            ['id' => 82,  'name_ar' => 'الانفطار',    'name_en' => 'Al-Infitar',    'name_transliteration' => 'Al-Infitar',    'total_ayahs' => 19,  'juz_start' => 30, 'page_start' => 587, 'revelation_type' => 'meccan'],
            ['id' => 83,  'name_ar' => 'المطففين',    'name_en' => 'Al-Mutaffifin',  'name_transliteration' => 'Al-Mutaffifin', 'total_ayahs' => 36,  'juz_start' => 30, 'page_start' => 587, 'revelation_type' => 'meccan'],
            ['id' => 84,  'name_ar' => 'الانشقاق',    'name_en' => 'Al-Inshiqaq',   'name_transliteration' => 'Al-Inshiqaq',   'total_ayahs' => 25,  'juz_start' => 30, 'page_start' => 589, 'revelation_type' => 'meccan'],
            ['id' => 85,  'name_ar' => 'البروج',      'name_en' => 'Al-Buruj',      'name_transliteration' => 'Al-Buruj',      'total_ayahs' => 22,  'juz_start' => 30, 'page_start' => 590, 'revelation_type' => 'meccan'],
            ['id' => 86,  'name_ar' => 'الطارق',      'name_en' => 'At-Tariq',      'name_transliteration' => 'At-Tariq',      'total_ayahs' => 17,  'juz_start' => 30, 'page_start' => 591, 'revelation_type' => 'meccan'],
            ['id' => 87,  'name_ar' => 'الأعلى',      'name_en' => "Al-A'la",       'name_transliteration' => 'Al-Ala',        'total_ayahs' => 19,  'juz_start' => 30, 'page_start' => 591, 'revelation_type' => 'meccan'],
            ['id' => 88,  'name_ar' => 'الغاشية',     'name_en' => 'Al-Ghashiyah',  'name_transliteration' => 'Al-Ghashiyah',  'total_ayahs' => 26,  'juz_start' => 30, 'page_start' => 592, 'revelation_type' => 'meccan'],
            ['id' => 89,  'name_ar' => 'الفجر',       'name_en' => 'Al-Fajr',       'name_transliteration' => 'Al-Fajr',       'total_ayahs' => 30,  'juz_start' => 30, 'page_start' => 593, 'revelation_type' => 'meccan'],
            ['id' => 90,  'name_ar' => 'البلد',       'name_en' => 'Al-Balad',      'name_transliteration' => 'Al-Balad',      'total_ayahs' => 20,  'juz_start' => 30, 'page_start' => 594, 'revelation_type' => 'meccan'],
            ['id' => 91,  'name_ar' => 'الشمس',       'name_en' => 'Ash-Shams',     'name_transliteration' => 'Ash-Shams',     'total_ayahs' => 15,  'juz_start' => 30, 'page_start' => 595, 'revelation_type' => 'meccan'],
            ['id' => 92,  'name_ar' => 'الليل',       'name_en' => 'Al-Layl',       'name_transliteration' => 'Al-Layl',       'total_ayahs' => 21,  'juz_start' => 30, 'page_start' => 595, 'revelation_type' => 'meccan'],
            ['id' => 93,  'name_ar' => 'الضحى',       'name_en' => 'Ad-Duha',       'name_transliteration' => 'Ad-Duha',       'total_ayahs' => 11,  'juz_start' => 30, 'page_start' => 596, 'revelation_type' => 'meccan'],
            ['id' => 94,  'name_ar' => 'الشرح',       'name_en' => 'Ash-Sharh',     'name_transliteration' => 'Ash-Sharh',     'total_ayahs' => 8,   'juz_start' => 30, 'page_start' => 596, 'revelation_type' => 'meccan'],
            ['id' => 95,  'name_ar' => 'التين',       'name_en' => 'At-Tin',        'name_transliteration' => 'At-Tin',        'total_ayahs' => 8,   'juz_start' => 30, 'page_start' => 597, 'revelation_type' => 'meccan'],
            ['id' => 96,  'name_ar' => 'العلق',       'name_en' => 'Al-Alaq',       'name_transliteration' => 'Al-Alaq',       'total_ayahs' => 19,  'juz_start' => 30, 'page_start' => 597, 'revelation_type' => 'meccan'],
            ['id' => 97,  'name_ar' => 'القدر',       'name_en' => 'Al-Qadr',       'name_transliteration' => 'Al-Qadr',       'total_ayahs' => 5,   'juz_start' => 30, 'page_start' => 598, 'revelation_type' => 'meccan'],
            ['id' => 98,  'name_ar' => 'البينة',      'name_en' => 'Al-Bayyinah',   'name_transliteration' => 'Al-Bayyinah',   'total_ayahs' => 8,   'juz_start' => 30, 'page_start' => 598, 'revelation_type' => 'medinan'],
            ['id' => 99,  'name_ar' => 'الزلزلة',     'name_en' => 'Az-Zalzalah',   'name_transliteration' => 'Az-Zalzalah',   'total_ayahs' => 8,   'juz_start' => 30, 'page_start' => 599, 'revelation_type' => 'medinan'],
            ['id' => 100, 'name_ar' => 'العاديات',    'name_en' => 'Al-Adiyat',     'name_transliteration' => 'Al-Adiyat',     'total_ayahs' => 11,  'juz_start' => 30, 'page_start' => 599, 'revelation_type' => 'meccan'],
            ['id' => 101, 'name_ar' => 'القارعة',     'name_en' => "Al-Qari'ah",    'name_transliteration' => 'Al-Qariah',     'total_ayahs' => 11,  'juz_start' => 30, 'page_start' => 600, 'revelation_type' => 'meccan'],
            ['id' => 102, 'name_ar' => 'التكاثر',     'name_en' => 'At-Takathur',   'name_transliteration' => 'At-Takathur',   'total_ayahs' => 8,   'juz_start' => 30, 'page_start' => 600, 'revelation_type' => 'meccan'],
            ['id' => 103, 'name_ar' => 'العصر',       'name_en' => 'Al-Asr',        'name_transliteration' => 'Al-Asr',        'total_ayahs' => 3,   'juz_start' => 30, 'page_start' => 601, 'revelation_type' => 'meccan'],
            ['id' => 104, 'name_ar' => 'الهمزة',      'name_en' => 'Al-Humazah',    'name_transliteration' => 'Al-Humazah',    'total_ayahs' => 9,   'juz_start' => 30, 'page_start' => 601, 'revelation_type' => 'meccan'],
            ['id' => 105, 'name_ar' => 'الفيل',       'name_en' => 'Al-Fil',        'name_transliteration' => 'Al-Fil',        'total_ayahs' => 5,   'juz_start' => 30, 'page_start' => 601, 'revelation_type' => 'meccan'],
            ['id' => 106, 'name_ar' => 'قريش',        'name_en' => 'Quraysh',       'name_transliteration' => 'Quraysh',       'total_ayahs' => 4,   'juz_start' => 30, 'page_start' => 602, 'revelation_type' => 'meccan'],
            ['id' => 107, 'name_ar' => 'الماعون',     'name_en' => "Al-Ma'un",      'name_transliteration' => 'Al-Maun',       'total_ayahs' => 7,   'juz_start' => 30, 'page_start' => 602, 'revelation_type' => 'meccan'],
            ['id' => 108, 'name_ar' => 'الكوثر',      'name_en' => 'Al-Kawthar',    'name_transliteration' => 'Al-Kawthar',    'total_ayahs' => 3,   'juz_start' => 30, 'page_start' => 602, 'revelation_type' => 'meccan'],
            ['id' => 109, 'name_ar' => 'الكافرون',    'name_en' => 'Al-Kafirun',    'name_transliteration' => 'Al-Kafirun',    'total_ayahs' => 6,   'juz_start' => 30, 'page_start' => 603, 'revelation_type' => 'meccan'],
            ['id' => 110, 'name_ar' => 'النصر',       'name_en' => 'An-Nasr',       'name_transliteration' => 'An-Nasr',       'total_ayahs' => 3,   'juz_start' => 30, 'page_start' => 603, 'revelation_type' => 'medinan'],
            ['id' => 111, 'name_ar' => 'المسد',       'name_en' => 'Al-Masad',      'name_transliteration' => 'Al-Masad',      'total_ayahs' => 5,   'juz_start' => 30, 'page_start' => 603, 'revelation_type' => 'meccan'],
            ['id' => 112, 'name_ar' => 'الإخلاص',     'name_en' => 'Al-Ikhlas',     'name_transliteration' => 'Al-Ikhlas',     'total_ayahs' => 4,   'juz_start' => 30, 'page_start' => 604, 'revelation_type' => 'meccan'],
            ['id' => 113, 'name_ar' => 'الفلق',       'name_en' => 'Al-Falaq',      'name_transliteration' => 'Al-Falaq',      'total_ayahs' => 5,   'juz_start' => 30, 'page_start' => 604, 'revelation_type' => 'meccan'],
            ['id' => 114, 'name_ar' => 'الناس',       'name_en' => 'An-Nas',        'name_transliteration' => 'An-Nas',        'total_ayahs' => 6,   'juz_start' => 30, 'page_start' => 604, 'revelation_type' => 'meccan'],
        ]);
    }
}
